### ISSUE TITLE
MultiPolygon is missing

### ISSUE THREAD

**Issue by deeplook** [Amyantis/python-vt2geojson#1]
Any plans for adding MultiPolygons, so this error would not show anymore?

`ValueError: 'MultiPolygon' is not a valid GeometryType`

**Comment by Amyantis** [comment]
Thank you for submitting your issue.

I can add a MultiPolygon handler. Can you provide a sample of a pbf file with MultiPolygons?

**Comment by deeplook** [comment]
At the moment I have only some proprietary content, but I can try to find something else.

**Comment by SheharBano20** [comment]
Hey Amyantis. Has this issue been resolved or not? I am still facing Multipolygon error. Is there anyway you can help?

**Comment by Amyantis** [comment]
I just released python-vt2geojson 2.0.0 thanks to https://github.com/Amyantis/python-vt2geojson/pull/2. MultiPolygon should now be handled properly.
